name: Build APK with Flutter

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Flutter with a specific version
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.0'  # 指定一个明确的版本号，而不是使用 stable

    # Cache Flutter dependencies
    - name: Cache Flutter dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.pub-cache
          ~/.flutter
        key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
        restore-keys: |
          ${{ runner.os }}-flutter-

    # Run Flutter build (APK)
    - name: Build APK
      run: |
        flutter pub get
        flutter build apk --release

    # Upload the APK as an artifact
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release.apk
        path: build/app/outputs/flutter-apk/app-release.apk
